Add check for successful plan

diff --git a/.github/workflows/deploy-workflow.yml b/.github/workflows/deploy-workflow.yml
--- a/.github/workflows/deploy-workflow.yml
+++ b/.github/workflows/deploy-workflow.yml
@@ -72,14 +72,15 @@ jobs:
       id: validate
       run: terraform validate -no-color
 
-    # generates a Terraform plan, This step only runs on pull requests. The PR generates a plan. When the PR is merged, that plan will be applied.
+    # generates a Terraform plan
     - name: Terraform Plan
       id: plan
       if: github.event_name == 'push'
       run: terraform plan -no-color
       continue-on-error: true
 
-    # adds a comment to the pull request with the results of the format, init and plan steps
+    # adds a comment to the pull request with the results of the format, init and plan steps, only works
+    # for a pull request
     - name: Update Pull Request
       uses: actions/github-script@0.9.0
       if: github.event_name == 'pull_request'
@@ -109,6 +110,11 @@ jobs:
             repo: context.repo.repo,
             body: output
           })
+
+    # make the workflow fail if the plan is not created correctly     
+    - name: Terraform Plan Status
+      if: steps.plan.outcome == 'failure'
+      run: exit 1
 
 
 
